### ISSUE TITLE
Flower breeding section/guide/tracker

### ISSUE THREAD

**Issue by Bonney** [Dimillian/ACHNBrowserUI#101]
This one was specifically requested by my wife :)

**Comment by TheVaan** [comment]
Just leaving a few information about breeding...

Background informations: https://docs.google.com/document/d/1ARIQCUc5YVEd01D7jtJT9EEJF45m07NXhAm4fOpNvCs/mobilebasic (happy reading)

Breeding-Cheat-Sheet: https://elkpon.tumblr.com/post/615443716368482304/finally-finished-making-this-tonight-the-data

**Comment by Dimillian** [comment]
So basically we want to make a pretty sheet explaining all that and have a link in the today dashboard. Sound good :)
