### ISSUE TITLE
iOS crash after attempting to enter turnip prices.

### ISSUE THREAD

**Issue by metalandcoffee** [Dimillian/ACHNBrowserUI#104]
Unfortunately this happened after I entered all my inventory 😓 but the app crashed and it would not let me back in. I had been entering my turnip prices after signing up for AC Helper+. So I deleted the app and re-downloaded it but it's not picking up that I am a subscriber anymore :-/

**Comment by Dimillian** [comment]
There was a version for a very short time with this issue on the App Store, I'm very it happen to you. Be sure to be updated to the latest version from the App Store. For restoring subscription status you can go in the settings from the dashboard and there is a restore purchase button :)

**Comment by metalandcoffee** [comment]
No worries! I'm thinking maybe me not updating to the latest iOS caused these issues too. You can close this. This hasn't happened again yet.
