### ISSUE TITLE
Load Turnip.Exchange listings conditionally.

### ISSUE THREAD

**Issue by metalandcoffee** [Dimillian/ACHNBrowserUI#105]
I'd personally prefer if the app are only loads listings if the user wants to see it (by tapping on a button) or if you maybe just load the first 5? What does everyone else think?

**Comment by Dimillian** [comment]
I think it's an excellent idea, I'll gate it behind a button that so you click it to load exchanges.

**Comment by ericlewis** [comment]
@Dimillian maybe gate it with a switch in settings.
