### ISSUE TITLE
iOS app crash when selecting certain villagers?

### ISSUE THREAD

**Issue by metalandcoffee** [Dimillian/ACHNBrowserUI#106]
I don't quite understand what's causing this issue. I recorded my screen and posted the video [here](https://metalandcoffee.com/wp-content/uploads/2020/05/ACNH-Bug-Villagers-Screen.mp4). When I search for 'Pudge' and click on them, it works fine. But when I go back to click on 'Puddles', the app crashes.

**Comment by Dimillian** [comment]
Are you on iOS 13.4+? Will take a look into it.

**Comment by metalandcoffee** [comment]
I’m on 13.3.1 but I will update to the latest.

**Comment by metalandcoffee** [comment]
Looks like this is still happening to me with the latest iOS so I'm not sure what's up. If I can provide anymore info, let me know.

**Comment by ericlewis** [comment]
@metalandcoffee is it certain villagers? or is it only when you tap on a villager, go back, and tap again that it fails?

**Comment by metalandcoffee** [comment]
It's for certain villagers. The ones that don't work for me far outweigh the ones that do. For instance, I'll search for Pudge and tap to see their profile. But if I scroll down to Puddles and tap, that's when the app just closes.

**Comment by Dimillian** [comment]
Could you update to latest update from the App Store and let us know? It should be fixed :)

**Comment by metalandcoffee** [comment]
I have version 1.1.2 installed. Is that the latest version? I don't have an update available from the App Store so I'm assuming that is the latest.

**Comment by Dimillian** [comment]
1.2 is the new one, I guess it’ll arrive soon :)

**Comment by metalandcoffee** [comment]
Yay! Ok sounds good. I'll wait for my app to update and check to see if it's fixed.

**Comment by metalandcoffee** [comment]
It's working perfectly now. Thanks @Dimillian !
