### ISSUE TITLE
Today’s Birthday doesn’t show today’s actual birthday

### ISSUE THREAD

**Issue by maeganjwilson** [Dimillian/ACHNBrowserUI#109]
Attached picture shows that the today’s birthday section doesn’t take into the actual date. Todays date is May 11, but the screenshot shows Nov 5. Yesterday it showed Oct 5. 
![ABEE81E5-A48B-494B-84F4-BFF29B22A688](https://user-images.githubusercontent.com/19311157/81566951-38117380-9361-11ea-95d3-449375061155.png)

**Comment by Dimillian** [comment]
Yes it's fixed by https://github.com/Dimillian/ACHNBrowserUI/commit/d5d369c5fe10654d167dd0a46bc9689c970e06bc and will be in next update :)

**Comment by maeganjwilson** [comment]
Awesome! I figured someone noticed, but just thought I’d mention.
