### ISSUE TITLE
Suggestion - turnip prices should update to show user input prices

### ISSUE THREAD

**Issue by maeganjwilson** [Dimillian/ACHNBrowserUI#110]
The turnip calculator shouldn’t say average prices for the time slot if the user has put in a value already. 
![26B39912-75C7-49DB-B154-1FB0C7ABADA0](https://user-images.githubusercontent.com/19311157/81567120-77d85b00-9361-11ea-96eb-a857970410a0.png)
In the screenshot above, it says the average for the morning is 98 bells but I already put in 95 bells as my price for this morning. It should say your price this morning is 95 bells sense there is already a price entered.

**Comment by Dimillian** [comment]
Make total sense, we'll do it :)

**Comment by maeganjwilson** [comment]
I'd like to also add this into the Turnips view. There shouldn't be an average shown if there's an actual data point. I'm taking a look at the source code to see if I could also easily submit a PR to "close" the issue. 

I love SwiftUI, so this is a great project! Thanks for the app!

**Comment by maeganjwilson** [comment]
Question how did you get the localizations? I adjusted some of the language to distinguish between average price and entered price.
