### ISSUE TITLE
Unable to Restore Purchases on iPhone

### ISSUE THREAD

**Issue by broncofan7** [Dimillian/ACHNBrowserUI#124]
Did the subscription on my iPad, tried the Restore Purchases on my iPhone (same AppleID), button does nothing. I don’t get a prompt or anything, just clicks away.

**Comment by Dimillian** [comment]
Looking into it. If you're on the same Apple Account it should actually be automatic. You can also try to subscribe again it'll work (and not subscribe you twice).
