### ISSUE TITLE
Crash on launch in Daashboard screen

### ISSUE THREAD

**Issue by pavm035** [Dimillian/ACHNBrowserUI#125]
When you launch the app it stars crashing in following methods
```struct TodayBirthdaysSection: View {
....
func birthdayDay(for villager: Villager) -> String {
....
let birthdayDate = formatter.date(from: birthday)!
}

func birthdayMonth(for villager: Villager) -> String {
....
 let birthdayDate = formatter.date(from: birthday)!
}
....
}
```

**Comment by Dimillian** [comment]
Fixed in latest commit. Sorry about that.

**Comment by pavm035** [comment]
> Fixed in latest commit. Sorry about that.

Is it pushed already, i don't see commit regarding this?

**Comment by Dimillian** [comment]
https://github.com/Dimillian/ACHNBrowserUI/commit/0f266be65ba2c42eed4ef7b7b61d835d853e607d Pull & run master it should works :)

**Comment by vianneychin** [comment]
The crash is happening on the live app as well unfortunately.

**Comment by Dimillian** [comment]
Yes, update is waiting for review...
