### ISSUE TITLE
Design Proposal: Overall UI & Data Visualisation for the turnip page 

### ISSUE THREAD

**Issue by alistairkb** [Dimillian/ACHNBrowserUI#129]
I cleaned up the UI a little;
![Dashboard](https://user-images.githubusercontent.com/8439821/81814681-a6218a80-955b-11ea-8305-a2f651730b03.png)

On the Turnips page, if the user has not entered personal prices;
![Turnips 1](https://user-images.githubusercontent.com/8439821/81814860-d8cb8300-955b-11ea-9fe4-0550a6b57f44.png)

Once the personal prices have been added to the turnip page, the user sees the following page;
![Turnips 2](https://user-images.githubusercontent.com/8439821/81815124-3364df00-955c-11ea-87b3-eb89a1064cbf.png)

I made the data more visual;
![Minimum - Maximum 2](https://user-images.githubusercontent.com/8439821/81815467-96567600-955c-11ea-9d87-5626ac98015e.png)
![Profits 2](https://user-images.githubusercontent.com/8439821/81815473-99516680-955c-11ea-86a1-6a3b6997380a.png)

**Comment by TheVaan** [comment]
I like your work but I think for an app with this topic it feels to „banking-app-like“. 
In my opinion this doesn‘t match totally to the user group (or to most of the user). The current design matches the in-game design pretty good. 
What I really like is the way of turnip price presentation.

**Comment by alistairkb** [comment]
Yeah, just wanted to try a clean design, see what people would think.

My main job was to design the turnip price section, so I'm glad you like it.
Will redesign with the current style in mind and reupload.
