### ISSUE TITLE
New wallpaper for the current design.

### ISSUE THREAD

**Issue by alistairkb** [Dimillian/ACHNBrowserUI#130]
![iPhone 11 Copy 5](https://user-images.githubusercontent.com/8439821/81817583-868c6100-955f-11ea-8c96-761132e03f01.png)
![iPhone 11 Copy 3](https://user-images.githubusercontent.com/8439821/81817599-8b511500-955f-11ea-860e-5c920559a75b.png)

**Comment by Bonney** [comment]
I'm not entirely sure that works with our current design – I do, however, like it _as a wallpaper_. And it might make a good launch image! Do you have higher-res versions?

**Comment by alistairkb** [comment]
I took the PNG from the animal crossing website with the ability to be scaled up/down.

My export settings weren't right, I can definitely do a bunch of these and let you choose from the best. Is there an exact file size you're after?

**Comment by alistairkb** [comment]
I think this size should be big enough.
![wallpaper](https://user-images.githubusercontent.com/8439821/81926746-0b858200-9615-11ea-84a4-e38f64ad90be.png)
