### ISSUE TITLE
Reproducible app crash

### ISSUE THREAD

**Issue by jordibruin** [Dimillian/ACHNBrowserUI#140]
Go to the catalog, select a category > swipe back > go to another category > go back by swiping but cancel the swipe half way through so you go back to the category screen. The app will become unresponsive. I think it's a SwiftUI bug as I'm seeing it in my SwiftUI app as well.

**Comment by ericlewis** [comment]
@jordibruin version you are on?

**Comment by Dimillian** [comment]
This is a SwiftUI bug anyway, nothing we can do about for now. @emcro Had some ideas but it require quite a bit of workarouds. Let's hope 13.5 fix it.
