### ISSUE TITLE
Language & Cataloguing Issue, App Ver 1.3 (051432020)

### ISSUE THREAD

**Issue by Kiyami218** [Dimillian/ACHNBrowserUI#141]
After the latest update, the language seems to have automatically changed to Chinese when accessing Fish & Bugs Catalogue as well as Art catalogue :(

Items marked off in Art Catalogue now aren't registering Marked Off in the [Chinese] list but also remains marked off in English list under Collection.

Any way to change back to English? (I couldn't find the option under Settings)
Or hopefully be fixed in next update :P Thank you!

![IMG_7125](https://user-images.githubusercontent.com/65439386/82112823-28948f00-9794-11ea-8357-7f6af913bf6b.PNG)
![IMG_7126](https://user-images.githubusercontent.com/65439386/82112824-29c5bc00-9794-11ea-8741-4d3e36a115cf.PNG)
![IMG_7127](https://user-images.githubusercontent.com/65439386/82112825-2a5e5280-9794-11ea-99aa-f427c81e7e27.PNG)
![IMG_7128](https://user-images.githubusercontent.com/65439386/82112826-2af6e900-9794-11ea-9063-5e7029fb8cce.PNG)
![IMG_7129](https://user-images.githubusercontent.com/65439386/82112827-2b8f7f80-9794-11ea-8042-a8cf95ce3a76.PNG)

**Comment by Dimillian** [comment]
It's fixed on master :) Will publish to the app store soon!

**Comment by Kiyami218** [comment]
Thank you for the prompt update, even moreso for the amazing work you've
done in the app ^^

**Comment by Dimillian** [comment]
Fixed in 1.3.1 waiting for review :)
