### ISSUE TITLE
Tableaux qui ne se compte pas

### ISSUE THREAD

**Issue by iDreamsX** [Dimillian/ACHNBrowserUI#149]
Lors de l'ajout des tableaux que je possède, ces derniers s'enregistrent, mais ne se comptent pas sur l'accueil et dans la progression de ma collection.
Application version 1.3 (051432020)

![IMG_0235](https://user-images.githubusercontent.com/37273978/82149061-60640b00-9856-11ea-8b10-b2db2c51e1c5.PNG)
![IMG_0237](https://user-images.githubusercontent.com/37273978/82149064-62c66500-9856-11ea-8aab-77e471efc50f.PNG)
![IMG_0238](https://user-images.githubusercontent.com/37273978/82149076-7376db00-9856-11ea-95d7-6f850a5cc68e.PNG)

**Comment by renaudjenny** [comment]
d'ailleurs, je viens de capter, Évènements... les accents, ils sont pas super correct si?
J'ai le jeu en anglais, donc j'ai pas fait gaffe (et j'ai pas super bien relue la traduction :/, désolé @Dimillian).
Je vais vite corriger ça dans une quick PR @Dimillian.

**Comment by iDreamsX** [comment]
Nous pouvons utiliser les deux types d'orthographes pour "Évènements"
Il a l'accent sur le deuxième è.
Nous pouvons écrire : "évènement" et "événement", cela n'est pas considéré comme une faute

**Comment by Dimillian** [comment]
Je viens de le corriger @renaudjenny :)

**Comment by Dimillian** [comment]
Et sinon la correction est dans la prochaine version :)

**Comment by Dimillian** [comment]
Fixed in 1.3.1
