### ISSUE TITLE
Everything is in Japanese?

### ISSUE THREAD

**Issue by reflectviolet** [Dimillian/ACHNBrowserUI#151]
When I opened my app today after the latest patch, all of my bugs and fish are named in what I believe is Japanese. My phone language is Canadian English / Canada for location.

**Comment by reflectviolet** [comment]
Edit: Now looking at the writing closer as opposed to just the update it seems like Japanese. Have attached a photo, not sure if it matters. 
![7275BD87-DEC7-4D86-8B63-170573D4F127](https://user-images.githubusercontent.com/65497961/82151259-ab672980-9828-11ea-923d-d66df7b1c7cf.png)

**Comment by renaudjenny** [comment]
Yep, we know :(. Fix is in review, see: https://github.com/Dimillian/ACHNBrowserUI/issues/141

**Comment by reflectviolet** [comment]
Thank you, sorry to bother you with another issue, I didn’t see that!

**Comment by renaudjenny** [comment]
@reflectviolet no worries :), hope Apple will accept the fix soon 🤞
