### ISSUE TITLE
Collection des différentes variantes d'items

### ISSUE THREAD

**Issue by iDreamsX** [Dimillian/ACHNBrowserUI#165]
Bonjour, 

Serait-il possible d'ajouter une option afin de pouvoir cocher les items que nous possédons dans leurs différentes variantes ?
Un système, directement sous l'item de base afin de pouvoir s'y retrouver suivant notre collection avec les couleurs des autres.
Cela pourrait aider beaucoup de monde dans la collection complète des items.

![IMG_0244](https://user-images.githubusercontent.com/37273978/82316516-31bc7080-99cd-11ea-98ab-d366896ee46c.PNG)

**Comment by ericlewis** [comment]
@Dimillian I can't read this, so it is on you!

**Comment by TheVaan** [comment]
@ericlewis as far as I understand, this is not bug but a feature request. @iDreamsX asks for a way to mark variants/colors of an item for the collection.

**Comment by Dimillian** [comment]
Yeah a lot of people have been requesting that and it make sense, in the collection we should save the item color / variant instead of the root item. i'll look into it.

**Comment by TheVaan** [comment]
So this is duplicate to #81?

**Comment by TheVaan** [comment]
Done with 7d58c7719f7f18f86e663b7c27db46312681b615
