### ISSUE TITLE
Timer Item Linked to Bunny Day Wand

### ISSUE THREAD

**Issue by Ruben-C** [Dimillian/ACHNBrowserUI#168]
Within the app looking at Catalog > Tools.  Selecting the Timer in the listing show info for the Bunny Day Wand.

Platform: iOS 13.5
Version: 1.4

Update:
Further testing shows this is something that occurs when you have an item selected then select from the list below an item marked “Same Color”.  Going back to this item will show the last selected item from “Same Color”

Reproduce:
1. Go to Catalog and select and item lets say “Timer”
2. Select a different item in the list below “Same Color”
3. Go back
4. Select item again “Timer” in this case
5. Item info provided is not “Timer” but the item selected in (2)

**Comment by Dimillian** [comment]
Nice catch!
