### ISSUE TITLE
Suggestion: Don't display turnip price averages or min/max values for days where data has been entered

### ISSUE THREAD

**Issue by daveverwer** [Dimillian/ACHNBrowserUI#171]
![Prices](https://user-images.githubusercontent.com/5180/82434782-4a8b5b80-9a8b-11ea-88d4-a86f54d1b2bf.png)

When turnip pricing data has been entered, it would seem sensible to display the actual price it was on those days rather than the average, or min/max prices. If data wasn't entered, maybe just a `-` for that day. It could also use a different colour for days that re real data, rather than predictions? Just to make it even clearer.

That way, at a glance, I can see which days my predictions are based on, and what those prices were. At the same time, it makes it clear that future days are predictions.

**Comment by Dimillian** [comment]
Totally on point, I think the ideal solution would be to display the - for average and the exact price in min - max / profits
It's in the work but we're not yet totally happy with it 
https://github.com/Dimillian/ACHNBrowserUI/pull/156

**Comment by daveverwer** [comment]
Fab! Feel free to close this if it's being taken care of in #156.

**Comment by daveverwer** [comment]
🚀

**Comment by Dimillian** [comment]
Yeah will be in next update :) thanks to @renaudjenny 
<img width="559" alt="Screenshot 2020-05-23 at 10 10 18" src="https://user-images.githubusercontent.com/535509/82725493-a5b48c80-9cdd-11ea-8140-5e709c010299.png">
<img width="559" alt="Screenshot 2020-05-23 at 10 10 20" src="https://user-images.githubusercontent.com/535509/82725498-a9e0aa00-9cdd-11ea-881d-5e6dab641e8e.png">
<img width="559" alt="Screenshot 2020-05-23 at 10 10 26" src="https://user-images.githubusercontent.com/535509/82725499-abaa6d80-9cdd-11ea-8692-cf54ba07d779.png">
