### ISSUE TITLE
Using of translation support service in l10n.

### ISSUE THREAD

**Issue by mimikun** [Dimillian/ACHNBrowserUI#174]
It is hard work to edit the file directly.
I think, it can solve this by using [Weblate](https://weblate.org) or [Crowdin](https://crowdin.com).

**Comment by TheVaan** [comment]
Hi @mimikun, this is true. We already discussed that but it’s not that easy. The useful services costs money for the amount of strings we have to translate. This doesn’t fit the OSS-hobby-character of this app. The free translation services that we found doesn’t match our needs. We continue looking for a service. Till then we „need“ to translate directly inside the files.
