### ISSUE TITLE
Extend app color to notch zone

### ISSUE THREAD

**Issue by raknam** [Dimillian/ACHNBrowserUI#180]
Heya :)

I think you should extend the app color over the notch. It will remove the white part and make UI more beautiful on X series :)

![IMG_3227](https://user-images.githubusercontent.com/1375001/82731171-45d1dc00-9d05-11ea-8fbb-e233ed422dc6.png)

**Comment by TheVaan** [comment]
Hey, this is an issue with your iOS version. You are on a version lower then 13.4, right? Apple fixed this bug. See here, iOS 13.5:
![55E084D8-937E-40B1-8931-16978B7DBBD8](https://user-images.githubusercontent.com/1108485/82731364-89791580-9d06-11ea-9d04-3e4b8788d787.png)

**Comment by raknam** [comment]
I confirm I'm on 13.3.1. I will upgrade and open back the issue if it is still occurs :)
Thanks for your quick answer @TheVaan
