### ISSUE TITLE
French translation misprint "villageois"

### ISSUE THREAD

**Issue by raknam** [Dimillian/ACHNBrowserUI#182]
Hello,

In french, villageois always get a **s** at the end, singular and plural.

![IMG_3228](https://user-images.githubusercontent.com/1375001/82751708-66f40480-9db9-11ea-98d3-f1a4714adf82.jpg)

**Comment by renaudjenny** [comment]
bien vu! @Dimillian do you want to fix it by directly pushing on master or could I create a PR?

**Comment by Dimillian** [comment]
Thanks! Fixing :)
