### ISSUE TITLE
White top bar

### ISSUE THREAD

**Issue by jackbentley** [Dimillian/ACHNBrowserUI#184]
For some reason, my app shows the top as white and doesn’t blend with the background. I’ve checked with my friend and theirs is the correct colour.

Device: iPhone XS

![9A840CDA-E25F-4F7F-B753-8493F1B9AAB6](https://user-images.githubusercontent.com/9383439/82759813-843fc780-9de7-11ea-824d-c1fa4c087ed9.jpeg)

**Comment by Dimillian** [comment]
You need to update your devices to iOS 13.4/13.5 to fix this issue :)
