### ISSUE TITLE
Collection Progress UI bug on launch

### ISSUE THREAD

**Issue by jackbentley** [Dimillian/ACHNBrowserUI#185]
Randomly when launching the app, some times the collection progress is collapsed partially.

Device: iPhone XS

![B1E3E34E-235A-4B29-B039-4B4A159661C1](https://user-images.githubusercontent.com/9383439/82759854-bd783780-9de7-11ea-91e1-ddec0241fb98.png)

**Comment by raknam** [comment]
I got the same. Not on random, but on app launch. If I close it when it is on background, wait 10/15 sec, then open the app.

**Comment by Dimillian** [comment]
It's fixed in the 1.4.5 aimed for mid next week :)

**Comment by Dimillian** [comment]
You can build & run master to try it out.
