### ISSUE TITLE
Invalid species on villagers

### ISSUE THREAD

**Issue by raknam** [Dimillian/ACHNBrowserUI#188]
Curly does not have the good species.

![image](https://user-images.githubusercontent.com/1375001/82764904-c0d4e880-9e12-11ea-92ba-901518b456f6.png)

**Comment by Dimillian** [comment]
It's on the API, will be fixed shortly without any app update :)

**Comment by Dimillian** [comment]
Fixed :)

**Comment by raknam** [comment]
Always good to get bugs self solving :D
