### ISSUE TITLE
Collection Tab Crash

### ISSUE THREAD

**Issue by BallisticFade** [Dimillian/ACHNBrowserUI#195]
Not sure if this has already been reported but clicking on the collection tab (furthest to the right) causes an immediate crash, this occurs every time the tab is clicked. I have checked to make sure it was not a one time crash but it is very reproduce-able

**Comment by Dimillian** [comment]
Are you on iOS 13.4 or 13.5 + latest app version?

**Comment by BallisticFade** [comment]
I am currently on iOS 13.4 + latest app version, I will update my iOS now
to see if this resolves the issue

**Comment by BallisticFade** [comment]
I have just updates to iOS 13.5 and the crash is still occurring every time
I try and open the collection tab

**Comment by Dimillian** [comment]
Can you show me the about screen of your AC Helper app? So I can see version / build number? Thanks!

**Comment by BallisticFade** [comment]
Of course, I’ll attach the screenshot to this email

**Comment by Dimillian** [comment]
Found an issue that could do that, will be fixed in 1.5.1 in a few days :)
