### ISSUE TITLE
Dashboard & TabView bug

### ISSUE THREAD

**Issue by JustCarousell** [Dimillian/ACHNBrowserUI#204]
On the Dashboard the change section order have some bug going on like shifting some of the order will crash the app like shifting the order of the AC Helper+ and when hiding the section after relaunch of the app causes duplication and also unhide the section on it’s own. Below is a picture for reference.  
![0688EC73-3BD1-45BF-8CFA-1FF54E570560](https://user-images.githubusercontent.com/66050990/83099310-92d7f880-a0df-11ea-91e4-c20f945853b3.jpeg)

For TabView is that everytime when you constantly go back and forth on certain tabs it will cause the wording of the title for the tab to be present and stacked up at the top. Below is a picture for reference.  
![97550987-081B-4D48-AF8A-3D6FEF0C7057](https://user-images.githubusercontent.com/66050990/83099324-9c616080-a0df-11ea-8e99-840a5dec91d9.jpeg)

iOS ver: 13.5 App ver: 1.6(052772020)

**Comment by Dimillian** [comment]
Yup @renaudjenny saw it too. Will fix :)

**Comment by dmndrz** [comment]
This bug is still not fixed in the latest release. Even after a clean install, the relaunch of the app still causes duplication and unhide sections. 😕

**Comment by dmndrz** [comment]
This bug is still not fixed in the latest release (1.6.2). Even after a clean install, the relaunch of the app still causes duplication and unhide sections. 😕

**Comment by Dimillian** [comment]
@dmndrz It'll be in 1.6.3 :) coming tomorrow.

**Comment by mimikun** [comment]
I still have this bug in my environment.
Many rows are duplicated.

<img src="https://user-images.githubusercontent.com/13450321/83698844-6e2ed400-a63d-11ea-9b5a-c3759e183b42.PNG" height="400px" width="auto" />

iOS ver: 13.5.1
App ver: 1.6.3

Do I need to uninstall the app and re-install?

**Comment by Dimillian** [comment]
@mimikun Yes sorry. If you have iCloud it'll restore your state on the launch. I'll try to add a cleanup methods to remove duplicates.

**Comment by mimikun** [comment]
Thanks.
Looking forward to the update.
