### ISSUE TITLE
Filter unmarked items

### ISSUE THREAD

**Issue by mimikun** [Dimillian/ACHNBrowserUI#211]
I want to filter of unmarked item.
I think, it will help collecting items.

**Comment by otaviocc** [comment]
I have a branch where I'm working on that :-) I might have something at the end of the day today.

**Comment by TheVaan** [comment]
@otaviocc are you still working on that or did you already pulled this? I lost the overview 😄

**Comment by otaviocc** [comment]
@TheVaan my bad, I never finished it. I'll resume the work. Sorry.

**Comment by TheVaan** [comment]
No problem! If you don’t have time to continue working on that you could also create a draft PR and someone else continues working on that.
