### ISSUE TITLE
villager gift ideas: not showing for Fuchsia

### ISSUE THREAD

**Issue by csardothien** [Dimillian/ACHNBrowserUI#218]
I have 10 villagers saved in my collection, the "gift ideas" section is showing for all villagers except Fuchsia. Network or parsing issue? Thanks!

A quick search: maybe related to this?

https://github.com/Dimillian/ACHNBrowserUI/blob/030dffd437322731d0478ed022314b0d99379454/ACHNBrowserUI/ACHNBrowserUI/views/villagers/VillagerDetailView.swift#L110-L126

`viewModel.preferredItems?.isEmpty` somehow becomes true for Fuchsia?

**Comment by Dimillian** [comment]
![Simulator Screen Shot - iPhone 8 - 2020-06-03 at 08 09 32](https://user-images.githubusercontent.com/535509/83601803-9b15b500-a571-11ea-83a7-5fd0fe63cb33.png)

This bug made me pull my hairs out, but now it's resolved and we have an even better matching and displaying at preferred gifts :)
