### ISSUE TITLE
Tooltips on Today’s Tasks?

### ISSUE THREAD

**Issue by metalandcoffee** [Dimillian/ACHNBrowserUI#223]
I love that there is a “Today’s Tasks” section ❤️❤️❤️ Thank you so much for this enhancement. But I must admit that I don’t know what all of them mean. Would it be possible to add some type of tooltip when you are pressing and holding on one of the tasks to get more info about it?

**Comment by TheVaan** [comment]
Hey,
I'm working on a feature where you can edit the tasks of the Today's Tasks section. There you'll see a name / short description. Would this be enough?
Short and long press are already assigned to other actions (short: increase progress; long: reset progress of single task).

**Comment by metalandcoffee** [comment]
@TheVaan that sounds perfect. I truly appreciate it :)

**Comment by TheVaan** [comment]
@metalandcoffee great! Let's test how this works. If you still need a tooltip I'll reopen this ticket and we're going to think about how we can do that.
