### ISSUE TITLE
Dashboard bug

### ISSUE THREAD

**Issue by dmndrz** [Dimillian/ACHNBrowserUI#224]
This bug is still not fixed in the latest release (1.6.2).
Even after a clean install, the relaunch of the app still causes duplication and unhide sections. 😕

_Originally posted by @dmndrz in https://github.com/Dimillian/ACHNBrowserUI/issues/204#issuecomment-638226235_

![IMG_ADD80BBB6F05-1](https://user-images.githubusercontent.com/18632343/83647721-80652f80-a5b5-11ea-86da-dbad26d4518e.jpeg)

**Comment by TheVaan** [comment]
The bug fix was commited 6 hours ago. It will be inside v1.6.3 that has been send to Apple 2 hours ago. Version 1.6.2 is 2 days old :)
