### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by ericlewis** [Dimillian/ACHNBrowserUI#23]
Automate delivery to TF. Use github actions / fastlane.

**Comment by ericblancas23** [comment]
what sorts of ci and github actions are you expecting?

**Comment by Dimillian** [comment]
Ideally we would want CI to build / test the app on each commit, and then have a manual action to ship to TestFlight. It'll need to update the build etc... But I'm not sure any of that can be on GH actions for now.

**Comment by renaudjenny** [comment]
@Dimillian you can have a look on one of my project, I did that recently: https://github.com/renaudjenny/telltime/blob/master/.github/workflows/xcodetest.yml
I use this library: https://github.com/pointfreeco/swift-snapshot-testing
That's the reason why I have to choose a very specific Emulator to test on (snapshot are taken with a kind of emulator and can obviously only being compare with the same model of emulator).
If we don't need Snapshot now, we can skip some step of this GitHub action.

**Comment by Dimillian** [comment]
I'm using it for my Swift package, but so the GH action support building and testing a full app? 
We def don't need to snapshot or event unit test for now. Actually a simple build status would be sufficient for now.

**Comment by Dimillian** [comment]
I'm testing GH actions here and it work really good :) https://github.com/Dimillian/SwiftUIFlux/blob/master/README.md

**Comment by Dimillian** [comment]
Thanks @renaudjenny added it on MovieSwiftUI from yours: 
https://github.com/Dimillian/MovieSwiftUI/runs/621811929?check_suite_focus=true
I think I'll do the same here, will be a good first step :)

**Comment by renaudjenny** [comment]
I'm glad you liked and used it even outside of this project! 😊

**Comment by ericlewis** [comment]
Considering this resolved.
