### ISSUE TITLE
Turnips

### ISSUE THREAD

**Issue by ericlewis** [Dimillian/ACHNBrowserUI#24]
This issue will be a master list of ideas for turnips. No particular order or priorities. 

- Turnip Calculator
- Turnip Charts
- Push notices
- Turnip Exchange

**Comment by Dimillian** [comment]
<img width="559" alt="Screenshot 2020-04-29 at 11 51 36" src="https://user-images.githubusercontent.com/535509/80585031-eb4da480-8a12-11ea-8e7f-d20f43f85a0d.png">
<img width="559" alt="Screenshot 2020-04-29 at 11 51 38" src="https://user-images.githubusercontent.com/535509/80585043-eee12b80-8a12-11ea-9433-dcf5beef1097.png">

Added that. Now we're only missing a charts and local notification :p

**Comment by Dimillian** [comment]
I've also added notifications now :D
