### ISSUE TITLE
Keyboard dissapear on type for 2nd level catalog

### ISSUE THREAD

**Issue by RSickenberg** [Dimillian/ACHNBrowserUI#243]
When I'm on a list of furniture for example and use the search bar, typing glitches the keyboard and makes him disappear. 

I would love to dig into it and try to fix it!

**Comment by TheVaan** [comment]
I can reproduce that. Seems to be a bug due to UI refresh.
You are welcome to fix it by your self! If you need any help tell us.

**Comment by RSickenberg** [comment]
@TheVaan I proposed a fix, it's to reuse the same search view as 1st level.

**Comment by Dimillian** [comment]
I'm on it :) Basically I'll allow search everywhere and it'll solve the problem that a conditional search bar cause.
