### ISSUE TITLE
Input Field Issues

### ISSUE THREAD

**Issue by otaviocc** [Dimillian/ACHNBrowserUI#244]
I don't remember seen this before, but maybe I'm wrong. When there's an input field, the text inside the field is right aligned, which makes it harder to tap (tapping on the input field positions the cursor at the beginning instead of end, which would be expected.). It also fails to capture blank spaces. Things get even harder when editing input field with numbers.

![01](https://user-images.githubusercontent.com/139272/84089524-785f2280-a9ef-11ea-9881-ec0685708868.gif)

![02](https://user-images.githubusercontent.com/139272/84089528-7b5a1300-a9ef-11ea-8391-0963707fbe83.gif)

Thanks!

**Comment by Dimillian** [comment]
Hmmm it didn't shocked me while using it on device, and it's a bit more estetically pleasing, but right for the turnip form it's a bit harder to use, @TheVaan you might want to recheck it.

**Comment by TheVaan** [comment]
I agree it’s not perfect. It didn’t felt wrong when I tested my changes. Alignment to the left looked really stupid... I’ll rethink how to get a good look and feel.

**Comment by TheVaan** [comment]
Fixed for turnip input in 87dc1ea5147f2bef2f90cfdb27c6b11df3c61dfe
Textfields on phone work bettern than in simulator. Let's wait for WWDC to see, if they will improve form view in SwiftUI.
