### ISSUE TITLE
Option to restore previous purchases ?

### ISSUE THREAD

**Issue by jbivia** [Dimillian/ACHNBrowserUI#264]
Is it possible to add an option to restore previous purchase of AC helper + ? I’ve bought the lifetime option and I can’t restore it after a reinstall since there’s no option for it

**Comment by TheVaan** [comment]
You don’t have the restore option in settings?

![image](https://user-images.githubusercontent.com/1108485/84618182-ba95d180-aed1-11ea-9aeb-6e5feab285f0.png)

**Comment by jbivia** [comment]
it is, my bad, I'm just blind
