### ISSUE TITLE
excuse me ,i download project not run in my Xcode

### ISSUE THREAD

**Issue by blantt** [Dimillian/ACHNBrowserUI#266]
excuse me ,i download project not run in my Xcode,
whenb preview,xcode show :
Select a scheme that builds a target which contains the current file, or add this file to a target that is built by the current scheme.

why it??  thks!

**Comment by TheVaan** [comment]
Don't know if this is what you are looking for, but you have to select "ACNHBrowserUI" as scheme and a iOS simulator next to the "play" button in Xcode.

**Comment by blantt** [comment]
thkank you very much ,i can run project!!

**Comment by TheVaan** [comment]
Perfect! I'll close this issue. Feel free to use this issue for further questions.
