### ISSUE TITLE
Alternative icon picker

### ISSUE THREAD

**Issue by ericlewis** [Dimillian/ACHNBrowserUI#27]
We have lots of icons! We need to support being able to choose alternatives. 

- convert images
- setup in project
- build UI under settings view

**Comment by Dimillian** [comment]
Can you package me all your icons ? Will look how to do it after.

**Comment by ericlewis** [comment]
https://t.co/lMz80OMtzB

**Comment by Bonney** [comment]
Anyone tackling this? I'd be glad to at least put together the UI for an icon picker, if someone wanted to integrate the logic. :)

**Comment by Dimillian** [comment]
You're more than welcome to tackle it :)

**Comment by Dimillian** [comment]
You can join our Slack here if you want to: https://join.slack.com/t/achelper/shared_invite/zt-dqu0apmb-rbV46xFvBvmXRYtp9JIoOQ
