### ISSUE TITLE
Label not updating when hitting this hedgehog looking guy

### ISSUE THREAD

**Issue by alext8900** [Dimillian/ACHNBrowserUI#272]
![DA6D9DB3-760F-4C6A-817E-B2B2BD880878](https://user-images.githubusercontent.com/53663334/85649766-93759780-b669-11ea-9a37-df9425d4042e.png)
![ED06EEE0-1462-40BA-87F4-D6562151E5F1](https://user-images.githubusercontent.com/53663334/85649771-96708800-b669-11ea-82a4-e1f7cb15a100.png)

**Comment by TheVaan** [comment]
Her name is „Label“. It comes from the French „la belle“ what means „the beautiful“. 
You can read her persona here:
https://nookipedia.com/wiki/Label

**Comment by alext8900** [comment]
Had no idea 😂, thought it was the basic label you get in an iOS app. Then
again I forget this app was developed in swift ui. My apologies

**Comment by TheVaan** [comment]
No problem 😁 I see that it could be a little bit confusing if you don’t know here already 😅
