### ISSUE TITLE
Music Player Animation

### ISSUE THREAD

**Issue by FaroukZeino** [Dimillian/ACHNBrowserUI#276]
**When sliding up the player, controls appear above TabBar instead of appearing from underneath:**

![RPReplay_Final1593394037](https://user-images.githubusercontent.com/33427443/85964224-76bac600-b9c1-11ea-935c-a99bfe304f80.gif)

**Comment by TheVaan** [comment]
Animations will be completely renewed within the iOS 14 release in september.
