### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by bilics** [Dimillian/ACHNBrowserUI#278]
Hi, 

Can't seem to build commit 3ac29a8 (see image attached)

MacOS 10.15.4
Xcode 11.5 (11E608c)

Is this commit restricted to Mac Big Sur (and iOS 14)?

<img width="267" alt="Screen Shot 2020-06-29 at 19 25 45" src="https://user-images.githubusercontent.com/1649572/86062171-7ca2bc80-ba3e-11ea-9a75-b16b619e914e.png">

Interesting to notice that (unlike previous versions) Package Dependencies are listing only these packages:

<img width="175" alt="Screen Shot 2020-06-29 at 19 27 42" src="https://user-images.githubusercontent.com/1649572/86062238-9fcd6c00-ba3e-11ea-93c8-9ba3741a2bf8.png">

Thanks!

**Comment by Dimillian** [comment]
Main branch is only for Xcode 12 beta 1. If you want to compile it on stable Xcode you'll need to try the legacy branch.

**Comment by bilics** [comment]
Thanks for the heads up!
