### ISSUE TITLE
Incorrect spawn times on July bugs

### ISSUE THREAD

**Issue by Braadlee** [Dimillian/ACHNBrowserUI#282]
Scarab beetle & Giant stag: 
App states: 13 - 08h 
Is actually: 23 - 08h

Walking stick:
App states: 04 - 08h
Is actually: 04 - 08h & 17 - 19hr

Evening cicada:
App states: 04 - 08h
Is actually: 04 - 08hr & 16 - 19h

(May be others wrong too but haven’t noticed yet)

**Comment by TheVaan** [comment]
We’re getting the data from a community source, so we don’t really have it in our hands what’s inside the dataset. We could change it, but it will be overwritten by further updates. We need to wait until the source is corrected.

**Comment by devilbeast** [comment]
@TheVaan any chance you could point us to the source so we can report the inaccuracy to them? I wasted quite a bit of time searching for the scarab and giant stag because I was going off the times listed in AC Helper and I'm sure I'm not alone.

**Comment by Dimillian** [comment]
I’ll do a re import in a while. The source is nookplaza API. The prickle is that the app don’t support multiple spawn time period for now. I’ll try to implement it :)

**Comment by Dimillian** [comment]
I've found a massive bug, it'll be resolved in 1.8.3 :)
