### ISSUE TITLE
Looks like typo

### ISSUE THREAD

**Issue by pavm035** [Dimillian/ACHNBrowserUI#297]
**souce code**
<img width="421" alt="Screen Shot 2020-07-11 at 15 30 34" src="https://user-images.githubusercontent.com/6092412/87218334-a5a34580-c38c-11ea-8393-43e184dbebd7.png">

**Comment by TheVaan** [comment]
Thank you very much!
🤦🏼‍♂️ how could we missed that?

I’ll fixing this.
