### ISSUE TITLE
Bug-Off Contest date incorrect

### ISSUE THREAD

**Issue by shpemu** [Dimillian/ACHNBrowserUI#298]
Hi there. Just switched to this app today and I’m loving it! Thank you! I had one error I wanted to request be fixed. I see the Bug-Off listed as July 18. The date should be July 25. ACNH (New Horizons) has this event every fourth Saturday, while ACNL (New Leaf) has it every third Saturday.

Thank you!

**Comment by ericlewis** [comment]
library for this is here: https://github.com/ericlewis/Date-ACNHEvents

**Comment by shpemu** [comment]
I don’t know what this means. I was using the app and was directed to post issues at GitHub. I don’t know how to edit the code for picking the bug off say, but it should be the 4th Saturday, not the 3rd. 

Thank you,
Sharon

**Comment by faizmokhtar** [comment]
@ericlewis @shpemu I'm quite interested to pick this up but I don't really have much of a context (the correct date) on this since I'm still a new Animal Crossing player. Will try to take a look on the library.

**Comment by shpemu** [comment]
The bug off happens every 4th Saturday instead of every 3rd Saturday. I just don’t know enough about how this code is written to properly update it. I hope that helps. 

Thank you,
Sharon Murphy
