### ISSUE TITLE
Collection progress list won’t save

### ISSUE THREAD

**Issue by daleaFox** [Dimillian/ACHNBrowserUI#299]
I was initially able to add in 36 fish that I’ve caught, to keep track. But afterwards whenever I add more they disappear as soon as I close the app this goes for bugs and sea creatures, and I’d assume everything else. They are all removed from the list when the app is closed. I can go back and add them back, but again they will just disappear. Hopefully this will be fixed soon.

**Comment by Dimillian** [comment]
Could you check if your iCloud Drive is full?

**Comment by TheVaan** [comment]
Closed due to missing response.
