### ISSUE TITLE
No way to go back from collections tab or active creatures

### ISSUE THREAD

**Issue by jkdabomb** [Dimillian/ACHNBrowserUI#318]
Once you click on the active creatures tab there’s no way to go back to the homepage, only way to go back is to close and reopen the app. Also can’t go back from opening up an individual creature or catalogue items.

**Comment by renaudjenny** [comment]
I experienced the same issue after updating to iOS 14. Don't worry, I heard that the app will be updated very soon 😉.

**Comment by TheVaan** [comment]
Should be fixed by e2dc77d

**Comment by jkdabomb** [comment]
The back button is there now. Only thing now the bugs category won’t load at all. No matter the length of time you wait for it to load.
