### ISSUE TITLE
Insect screen hangs in “active critters” view 

### ISSUE THREAD

**Issue by devilbeast** [Dimillian/ACHNBrowserUI#323]
In iOS/iPadOS 14.0.1, the insect screen in the “active critters” view never loads. I’m using version 2.0.2 of the app, game patch version 1.3.0.

![F680EF54-6E74-4E0A-BD3D-C603FDDD6FA1](https://user-images.githubusercontent.com/67984817/94378157-fef15a00-00db-11eb-89c8-68ebf4e20370.jpeg)

**Comment by renaudjenny** [comment]
Do you, by any chance, caught all critters of a kind? I mean for instance, caught all the insects, or all fish?
In that case, it could be a duplicate of this ticket: https://github.com/Dimillian/ACHNBrowserUI/issues/321 and it's already been fixed 🎉 and it would be available in the next publication of the app.

Let us know if it's something else, and how can we reproduce?

Thanks.

**Comment by devilbeast** [comment]
@renaudjenny You’re absolutely right — I had collected all the insects. Later this evening, I caught the remaining active fish and sea creatures, and now those tabs hang as well. Sounds like a duplicate of #321. Thanks!

**Comment by renaudjenny** [comment]
I wish I could catch all fish 😞, I still have these bloody Sturgeon and Giant Trevally to catch 😂

**Comment by devilbeast** [comment]
I hear you! After _months_ of fishing, I finally caught the barrel eye last night! It just refused to spawn!
