### ISSUE TITLE
Unable to Download

### ISSUE THREAD

**Issue by kevinwpq3** [Dimillian/ACHNBrowserUI#332]
I’m unable to download newest version update from App Store.

Push update button get circle icon up spins to about 40% then update button pops back

**Comment by renaudjenny** [comment]
This is weird, as the download is managed by the AppStore (Apple).
Please check if you still have enough free space to install it or try to restart your iPhone.
Did you try to download/update another application of ~45 MB by any chance?

**Comment by Dimillian** [comment]
Are you on iOS 14?

**Comment by kevinwpq3** [comment]
Running version 14.1 and have over 200GB available

**Comment by TheVaan** [comment]
This sounds weird. As mentioned before, update process is managed by App Store. 
If you have iCloud enabled you can delete and reinstall app without loosing your data. 
Or you can try a soft reset (restart iPhone with volume up, volume down, off-button) and test if it works after soft reset.

**Comment by TheVaan** [comment]
@kevinwpq3 Anything new with your issue? Is updating still not possible?

**Comment by TheVaan** [comment]
Closed issue. No response for about 3 weeks. App updating is part of App Store, not of the app.
