### ISSUE TITLE
Today’s Birthday infinite spinning

### ISSUE THREAD

**Issue by nacmcfeegle** [Dimillian/ACHNBrowserUI#334]

**Comment by renaudjenny** [comment]
Hi @nacmcfeegle, thank you for reporting this bug.
Unfortunately, it's hard to understand what exactly happens to you.
I believe this could be related to the bug #330 ? Tell me otherwise.

About the #330 and other mentioned bugs in it, it is fixed on `main` branch, and the fix should be available soon via an AppStore update.

Will keep you in touch when it will.

Thanks Again :).

**Comment by nacmcfeegle** [comment]
I don’t think I’ve caught all active critters - I haven’t played for a few weeks and right hand menu bar says there is at least 1 new critter in each category that I haven’t caught. Critters page doesn’t show anything - just the spinning wheel.

**Comment by nacmcfeegle** [comment]
![IMG_0238](https://user-images.githubusercontent.com/73749369/97782636-8e31d780-1b8a-11eb-9b9a-9bc4d8503cf0.png)

Today’s birthdays also appears to be spinning but was working earlier.

PS thanks for the super quick response!

**Comment by renaudjenny** [comment]
Actually since the last update (2.0.3), I (sorry) broke the entire Critters view :(, even if you haven't caught all the critters.
But in the future one, everything is fixed 😅. We submitted to review very recently.
However, I didn't know about the Today's Birthday.

**Comment by nacmcfeegle** [comment]
Haha! Ok, sorry didn’t realise... just a case of waiting until it’s approved then?

I updated my residents this morning - today’s birthday was showing as Tex’s birthday when i opened up the app, which I think was a couple of weeks ago. When I updated residents, it’s now just spinning.

Great app, btw. I did notice another bug previously on the catalogue but didn’t know how to report. Now I do I’ll check if it’s still there and let you know if so!

**Comment by renaudjenny** [comment]
> just a case of waiting until it’s approved then?

Yes... hopefully it will be today.

I just noticed that I experience the same issue with my Today's Birthday as well (infinite spinning). I will have a look.

If I may, I could use this ticket for that, could you edit the title to reflect The Today's Birthday infinite spinning? Thank you :)

**Comment by nacmcfeegle** [comment]
Done!

**Comment by renaudjenny** [comment]
Thanks a lot, and believe it or not... There is no birthday today :D 
That's the reason there is an infinite spinner there, it's because we haven't handle no birthday... 😂.
I will fix this issue... but tomorrow it would be fine anyway I guess...

**Comment by Dimillian** [comment]
Update is out :)
