### ISSUE TITLE
Crash when trying to touch something in a list after using text field on macOS

### ISSUE THREAD

**Issue by renaudjenny** [Dimillian/ACHNBrowserUI#38]
It seems that my fix to dismiss automatically the keyboard lead to a crash on macOS :(

I think I will add some `#if os(macOS)` on the ViewModifier as there is no keyboard that pops, so no need to apply the ViewModifier there.

**Comment by Dimillian** [comment]
Yup you should actually. Our catalyst build works because it was literally one toggle. Apple didn't lied. But it's not really supported yet. But as we don't have soft keyboard on mac I guess you should disable it on macOS right :)
