### ISSUE TITLE
Flashing

### ISSUE THREAD

**Issue by vvalembois** [Dimillian/ACHNBrowserUI#40]
Hi, 

There is a flashing when changing views through the tabBarController isn't there any way to make a small animation?

Regards 

PS: Sorry for the multiple issue regarding the iOS version, the github mobile application told me that the issue was not created.

**Comment by ericlewis** [comment]
@vvalembois the problem existing here is an issue with SwiftUI. It is possible to prevent the flashing, but it causes changes in how navigation works (i.e. pushing a detail screen causes the tab bar to be hidden). Maybe we wait for WWDC and see if they helped us out :)

**Comment by vvalembois** [comment]
Hi,

I also have this problem on a SwiftUI personal project but I created the issue to have a trace and thus correct this problem later ;)

Regards
