### ISSUE TITLE
Navigation Title and item ghosts remain after partially been navigated back

### ISSUE THREAD

**Issue by renaudjenny** [Dimillian/ACHNBrowserUI#41]
It's happening when using the "go back" gesture (swipe from left of the screen to the centre). No problems when tapping on the go back button though.

![image](https://user-images.githubusercontent.com/2297556/79914941-fce4ea00-841d-11ea-968e-75918ec29577.png)

**Comment by Dimillian** [comment]
I'll call SwiftUI bug on this one :/

**Comment by renaudjenny** [comment]
That's what I thought :(. Hope they will fix it in SwiftUI 2!

**Comment by ericlewis** [comment]
Also think this is SwiftUI, we just use NavigationViews.
