### ISSUE TITLE
Update data to 1.2.0 game patch

### ISSUE THREAD

**Issue by Dimillian** [Dimillian/ACHNBrowserUI#48]
@ericlewis is in the process of migrating our static JSON files dumped from https://nookplaza.net/ a while ago to full featured CoreData database. 
Upgrading to new Nook Plaza dump should be a breeze after that.

**Comment by ericlewis** [comment]
this is part of the ongoing CD effort which can be seen here: https://github.com/Dimillian/ACHNBrowserUI/pull/33

**Comment by Dimillian** [comment]
I couldn't resist a did a new dump of the API and adapted our models. Things are a bit simpler critters now. We also got some new features.

**Comment by ericlewis** [comment]
I am calling this done, reopen if you want @Dimillian
