### ISSUE TITLE
Reorganize Settings screen

### ISSUE THREAD

**Issue by Bonney** [Dimillian/ACHNBrowserUI#58]
I plan on doing on work on the Settings view; try to clean up the island details (maybe pull that in to it's own view); leave the door open for any future preferences we need to integrate

**Comment by Dimillian** [comment]
Adding to that: I would love to use the info you can enter in settings screen to generate a cool card on the dashboard with an avatar (you can upload) and island name, fruits etc... So you can share it around. I might do that next. Because for now the info are a bit useless.

**Comment by Bonney** [comment]
I like that. If you don’t get to it, I will!!

**Comment by Bonney** [comment]
> Adding to that: I would love to use the info you can enter in settings screen to generate a cool card on the dashboard with an avatar (you can upload) and island name, fruits etc... So you can share it around. I might do that next. Because for now the info are a bit useless. 

I’ve actually got something you might like.... I will polish over the next few days
