### ISSUE TITLE
Turnips chart tab

### ISSUE THREAD

**Issue by Dimillian** [Dimillian/ACHNBrowserUI#59]
Something like that would be cool:
![Screenshot 2020-04-29 at 20 58 37](https://user-images.githubusercontent.com/535509/80635572-596a8980-8a5c-11ea-9486-4b37f498a301.png)

You can try it here: 
https://ac-turnip.com/

**Comment by renaudjenny** [comment]
I could really give a try as I love working with `Path`. But if anyone else want to tackle this, please do 😊. At least I could help them!
