### ISSUE TITLE
Crashes when tapping on Villagers tab

### ISSUE THREAD

**Issue by pwightman** [Dimillian/ACHNBrowserUI#62]
Not sure what more info to provide, or if this is even how you prefer this feedback, but I'm on an iPhone 11 Pro. Install app -> tap each tab until I get to Villagers -> crash.

**Comment by ericlewis** [comment]
Can confirm this is reproducible. 

It appears that UserCollection’s existence can cause a race condition. 

A proposed fix would be to drill down and use a singleton.

**Comment by Dimillian** [comment]
Or we could try to force passe it as .environmentObject to every tab.

**Comment by ericlewis** [comment]
@Dimillian that is what I said :P but instead a singleton (shared) so that init happens once on launch. Drill down = per tab.

**Comment by TheVaan** [comment]
Problem should be solved a few commits ago.
