### ISSUE TITLE
Turnips UI issue

### ISSUE THREAD

**Issue by golles** [Dimillian/ACHNBrowserUI#63]
Hi, first, thanks for this great app! I use it a lot while playing the game.
After updating the turnip price this afternoon, the UI looked like this:
![image0](https://user-images.githubusercontent.com/2211503/80805045-37394e80-8bb7-11ea-91a8-017298270715.png)

I can't reproduce it at the moment

**Comment by Bonney** [comment]
I _think_ this is due to rotation between portrait and landscape. The entire turnip UI is a big work in progress that I plan on working on over the weekend, thanks for the heads up 👍

**Comment by Dimillian** [comment]
Yep I can reproduce turning my phone. 
We"ll disable rotation on iPhone tho, doesn't make sense.

**Comment by Dimillian** [comment]
The rotation is now blocked on iPhone so this solve this issue :)
