### ISSUE TITLE
Turnips chart improvement

### ISSUE THREAD

**Issue by Dimillian** [Dimillian/ACHNBrowserUI#77]
* [x] Add +50/-50 (not below 0) to the minMax spread so it have space to breath
* [x] Scroll the Y legend with the content? (need to test)
* [ ] Curved lines

**Comment by renaudjenny** [comment]
Hi @Dimillian, I added some extra steps (±50 and not below 0). Tell me if it's OK for you.

For the other task... I'm not sure as we are already in a Vertical ScrollView (the List), and we scroll already horizontally, I'm worried that could be complicated for the user to understand what's scrolling.

![image](https://user-images.githubusercontent.com/2297556/81143634-319e8880-8f6a-11ea-8197-df136edf068e.png)

**Comment by Dimillian** [comment]
I think you're right, it'll be too complicated to look at if we make the Y legend static.

**Comment by Dimillian** [comment]
This +50/-50 look good! 
What do you think about curved lines? So the path point connect with an arc instead of just point to point.

**Comment by renaudjenny** [comment]
I would love "flatten the curve"... Sorry, I had to say that...

**Comment by Dimillian** [comment]
Very relevant 🥇
