### ISSUE TITLE
Tabs Navigation Stack Resets

### ISSUE THREAD

**Issue by chitvan832** [Dimillian/ACHNBrowserUI#78]
**Expected Behaviour:** When I switch between tabs on TabView, each tab should maintain its own Navigation Stack.

**Current Behaviour:**
When i switch beteween tabs, they always show me the rootView.

**Example:** On Villagers tab if I go to some villagers details Screen and then click on Dashboard and come back to Villagers tab, it shows me Villagers list, instead of Detail View. This is happening for all the tabs

**Comment by Dimillian** [comment]
You're totally right, and unfortunately this is how the SwiftUI `TabView` works at the moment. I'll dig into it to see if we could do any workaround.

**Comment by jordibruin** [comment]
@Dimillian I found a solution for this which basically wraps UIKit's UITabBar into it. It's not perfect but it works for this particular bug. 

Have a look 🙂 
https://gist.github.com/Amzd/2eb5b941865e8c5cccf149e6e07c8810

**Comment by makirby** [comment]
@Dimillian we've been using [this](https://github.com/NicholasBellucci/StatefulTabView) to give us the desired functionality, was basically a drop in replacement for the TabView
