### ISSUE TITLE
Categorize items added into my stuff

### ISSUE THREAD

**Issue by Dimillian** [Dimillian/ACHNBrowserUI#82]
My stuff' -"items" section could have the folders of specifics since there are a ton of items eg; flooring, wallpaper, furniture, etc

> From a fellow Reddit user

**Comment by ericlewis** [comment]
Yes, favorites should be similar to categories, and also should show the counts for each category and/or only show categories with favorites.

**Comment by Dimillian** [comment]
Fixed by https://github.com/Dimillian/ACHNBrowserUI/pull/142
